name: urban-mcp

services:
  mcp:
    container_name: urban_mcp
    build:
      context: ..
      dockerfile: urban_mcp/Dockerfile
    restart: on-failure
    ports:
      - ${EXPORT_MCP_PORT:-8001}:${PORT:-8001}
    environment:
      - MCP_CONFIG_PATH=/app/config.yaml
    volumes:
      - ./logs:/app/logs
      - ${REAL_MCP_CONFIG_PATH}:/app/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
